// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OnlineTeach.Web.Data;
using System;

namespace OnlineTeach.Web.Data.Migrations
{
    [DbContext(typeof(AdultDbContext))]
    partial class AdultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineTeach.Web.Data.Adult.TeacherApply", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplyCount");

                    b.Property<string>("ApplyReason");

                    b.Property<DateTime>("ApplyTime");

                    b.Property<string>("Name");

                    b.Property<string>("RealName");

                    b.Property<string>("School");

                    b.Property<Guid>("userId");

                    b.HasKey("Id");

                    b.ToTable("TeacherApplies");
                });
#pragma warning restore 612, 618
        }
    }
}
